# Generated by Django 4.2.24 on 2025-09-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobtaskequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=2),
        ),
    ]
