# Generated by Django 4.2.24 on 2025-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('jobs', '0003_alter_job_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtask',
            name='required_equipment',
        ),
        migrations.AddField(
            model_name='jobtask',
            name='required_equipment',
            field=models.ManyToManyField(blank=True, related_name='required_by_tasks', to='equipment.equipment'),
        ),
    ]
