# Generated by Django 4.2.24 on 2025-09-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobtask_required_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.DeleteModel(
            name='JobTaskEquipment',
        ),
    ]
