# Generated by Django 4.2.24 on 2025-09-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobtask_status_delete_jobtaskequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
